### ISSUE TITLE
Sprint / Waterfall

### ISSUE THREAD

**Issue by cprkrn** [HashtagTeamName/q#7]
Three week cycle:

**Comment by cprkrn** [comment]
Week 1: Implement base web app. Get visuals to actually test things.

**Comment by cprkrn** [comment]
Week 2: Finish base web app. Implement functionality of web app. Get some database stuff going

**Comment by cprkrn** [comment]
Week 3: Finish database implementation. Start testing.

**Comment by superfully** [comment]
Looks like we're making progress..

**Comment by cprkrn** [comment]
I think we're past this point yeah?
