### ISSUE TITLE
Create an Infographic

### ISSUE THREAD

**Issue by Kyle-Helmick** [HashtagTeamName/q#8]
Check Oct 24 slides for info.

**Comment by cprkrn** [comment]
Working on it. Can somebody link me to the slide? Not really seeing anything other than lab slides for that week.

**Comment by cprkrn** [comment]
![infograph_draftuno](https://cloud.githubusercontent.com/assets/9752976/19871605/3d957f96-9f7b-11e6-8f34-6746f739d612.png)
// post updated infographs here so we can keep track of progress!

**Comment by cprkrn** [comment]
// moved to new issue
